### ISSUE TITLE
Implement Name Detection

### ISSUE THREAD

**Issue by jrbonds** [NCATComp410/comp410_summer_2023#11]
**Definition:**
Your name is a phrase that will be tied to many different types of data, certificates, devices and other forms of PII for your entire life. It's the fabric that ties who you are to things like your social security number, bank account info, lease agreements and much more. Your name, if correctly identified, is the first piece of invaluable data that can be used in conjunction with other forms of PII that can lead to identity theft, fraud, personal harm, etc. Hence the need for name changes or an alias' for witness protection and government services. In the right cases, protecting your name means protecting your true identity and reduces the risk of a security breach or any other malicious intent.

**Example:**
Johnny Appleseed , Emily Smith , Floyd Mayweather, Jr.

Detection Steps:
Python code will be written with the intent of detecting the first and last name of the user. The user will be asked if they identify as a 'Mr.' , 'Ms.' or 'Mrs.' . The program will also ask if there are any suffix's included in the name such as 'Jr.' , 'I' , 'II' , etc. Names in the order of the example will be accepted.

**Comment by claesmk** [comment]
Since you will be scanning some text for possible names you will not have an opportunity to ask the user for additional details such as what they identify as or any suffixes. 

However, in the case where a name match might not be particularly strong, it might be OK to prompt the user to see if they believe it is a name or not. That would help reduce the potential for "leaks" caused by missed detections.

**Comment by adomakk** [comment]
Will the python code be able to detect if the name is hyphenated?

**Comment by jrbonds** [comment]
I see. Understood.

**Comment by jrbonds** [comment]
Yes the program will be able to detect hyphenated names.
